export const IMAGEPATH = {
  // ------------------ splash ------------------
  // Splash: require('../Images/Splash/SplashIMAGE.png'),
  CommonImage: require("../Images/Background/globalbackgroundImg.png"),
  LogoMain: require("../Images/Splash/LOGO.png"),
  IntroVidio: require("../Images/Splash/Video.png"),
  ProfilePic: require("../Images/DrawerImages/DummyProfile.png"),
  HomeHeder: require("../Images/Background/HomeTitlePng.png"),
  HomeOnlineBackPng: require("../Images/Background/HomeOnlinePng.png"),
  BlureBackPng: require("../Images/Background/BlureBackPng.png"),
  DriverImage: require("../Images/Background/DriverImage.png"),
  DummyDriverImage: require("../Images/DrawerImages/DummyProfile.png"),
  CancelImage: require("../Images/Home/Cancle.png"),
  BackImageDRAWER: require("../Images/DrawerImages/DrawerBack.png"),
  LOGOUT: require("../Images/DrawerImages/LogOutImage.png"),
  SETTING: require("../Images/DrawerImages/settings.png"),
  HOMEDrawer: require("../Images/DrawerImages/HOME.png"),
  MyAccDRAWER: require("../Images/DrawerImages/MyAcc.png"),
  DashbordDRAWER: require("../Images/DrawerImages/Dashboard.png"),
  Plans: require("../Images/DrawerImages/plans.png"),
  Success: require("../Images/Background/Success.png"),
  Cross: require("../Images/Home/Cross.png"),
  MAP: require("../Images/Splash/MapSplash.png"),
  Chat1: require("../Images/Home/ChatONE.png"),
  Chat2: require("../Images/Home/ChatTWO.png"),
  Chat3: require("../Images/Home/ChatTHREE.png"),
  Chat4: require("../Images/Home/ChatFour.png"),
  LoginBG: require("../Images/Background/LoginBG.png"),
  Background: require("../Images/Background/Bg.png"),
  LocationMarker: require("../Images/DrawerImages/marker.png"),
  message: require("../Images/Home/Message.png"),
  notices: require("../Images/Home/Notices.png"),
  account: require("../Images/Home/Account.png"),
  ratings: require("../Images/Home/ratings.png"),
  docs: require("../Images/Home/docs.png"),
  suggestFriends: require("../Images/Home/suggestFriends.png"),
  announcements: require("../Images/Home/announcements.png"),
  User: require("./Profile_Images/ProfileImage.png"),
  Language: require("./DrawerImages/Language.png"),
};
